apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5672
          env:
            # From Secret
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_DEFAULT_USER
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_DEFAULT_PASS
          resources:
            limits:
              memory: "128Mi"
              cpu: "300m"
---
kind: Service
apiVersion: v1
metadata:
  name: rabbitmq-cip-service
spec:
  selector:
    app: rabbitmq
  ports:
    - protocol: TCP
      port: 5672
  type: ClusterIP
