apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-configmap
data:
  DB_TYPE: "MYSQL"
  JWT_ALGORITHM: "HS256"
  TOKEN_EXPIRY_TIME: "15"

  PASSWORD_LENGTH: "4"
  CELERY_BROKER_URL: "amqp://guest:guest@rabbitmq-cip-service:5672/"
  CELERY_RESULT_BACKEND: "redis://redis-cip-service:6379/0"

  LOG_CONFIG_FILE: "./app/config/logging.conf"
  LOGS_DIR: "/tmp/fast-api-template"
  LOG_FILE_NAME: "api.log"

  MAIL_SENDER_NAME: ""
  MAIL_SENDER_EMAIL: ""

  # MySql
  MYSQL_HOST: "mysql-cip-service"
  MYSQL_DB: "apptemplate"
  MYSQL_PORT: "3306"
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
stringData:
  SECRET_KEY: ""
  MYSQL_USER: ""
  MYSQL_PASSWORD: ""
