apiVersion: v1
kind: ConfigMap
metadata:
  name: worker-configmap
data:
  CELERY_BROKER_URL: "amqp://guest:guest@rabbitmq-cip-service:5672"
  CELERY_RESULT_BACKEND: "redis://redis-cip-service:6379/0"
  SMTP_SERVER: ""
  SMTP_PORT: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: worker-secret
type: Opaque
stringData:
  SMTP_USER_NAME: ""
  SMTP_PASSWORD: ""
